// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TheDbContext))]
    partial class TheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.EInvoices.EInvoice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<string>("CustomerTaxCode")
                        .HasColumnType("text")
                        .HasColumnName("customer_tax_code");

                    b.Property<long>("InvoiceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceNumber"));

                    b.Property<string>("InvoiceSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_symbol");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lookup_code");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("OrgAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_address");

                    b.Property<string>("OrgLogo")
                        .HasColumnType("text")
                        .HasColumnName("org_logo");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_name");

                    b.Property<string>("OrgPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_phone");

                    b.Property<string>("OrgStamp")
                        .HasColumnType("text")
                        .HasColumnName("org_stamp");

                    b.Property<string>("OrgTaxCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("org_tax_code");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("text")
                        .HasColumnName("qr_code_url");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_total");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalWithTax")
                        .HasColumnType("numeric")
                        .HasColumnName("total_with_tax");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("VatPercent")
                        .HasColumnType("integer")
                        .HasColumnName("vat_percent");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_e_invoice");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_e_invoice_id");

                    b.ToTable("e_invoice", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.EInvoices.EInvoiceItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("e_invoice_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitRelationName")
                        .HasColumnType("text")
                        .HasColumnName("unit_relation_name");

                    b.HasKey("Id")
                        .HasName("pk_e_invoice_item");

                    b.HasIndex("EInvoiceId")
                        .HasDatabaseName("ix_e_invoice_item_e_invoice_id");

                    b.ToTable("e_invoice_item", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("FundBehaviorId")
                        .HasColumnType("bigint")
                        .HasColumnName("fund_behavior_id");

                    b.Property<object>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_fund");

                    b.HasIndex("FundBehaviorId")
                        .HasDatabaseName("ix_fund_fund_behavior_id");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_fund_object_id");

                    b.ToTable("fund", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundBehavior", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Automatic")
                        .HasColumnType("boolean")
                        .HasColumnName("automatic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Generate")
                        .HasColumnType("boolean")
                        .HasColumnName("generate");

                    b.Property<object>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_fund_behavior");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_behavior_id");

                    b.ToTable("fund_behavior", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<object>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("TransactionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_at");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_transaction_customer_id");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.BranchUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_branch_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_branch_user_user_id");

                    b.ToTable("branch_user", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AvtUrl")
                        .HasColumnType("text")
                        .HasColumnName("avt_url");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birth_day");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte?>("CustomerGroup")
                        .HasColumnType("smallint")
                        .HasColumnName("customer_group");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_user_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.EInvoices.EInvoiceItem", b =>
                {
                    b.HasOne("Domain.Aggregates.EInvoices.EInvoice", "EInvoice")
                        .WithMany("Items")
                        .HasForeignKey("EInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_e_invoice_item_e_invoice_e_invoice_id");

                    b.Navigation("EInvoice");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.HasOne("Domain.Aggregates.Funds.FundBehavior", "FundBehavior")
                        .WithMany()
                        .HasForeignKey("FundBehaviorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_fund_behavior_fund_behavior_id");

                    b.HasOne("Domain.Aggregates.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .HasConstraintName("fk_fund_user_object_id");

                    b.Navigation("FundBehavior");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Transaction", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_user_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.BranchUser", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", null)
                        .WithMany("BranchUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_user_user_user_id");
                });

            modelBuilder.Entity("Domain.Aggregates.EInvoices.EInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("BranchUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
