version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Admin@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - rd_data:/data
    restart: always
  auth-service:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: auth-service
    ports:
      - "5001:80"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${AUTHDB_CONNECTION}
      - Jwt__Key=${Key}
      - Jwt__Issuer=${Issuer}
      - Jwt__Audience=${Audience}
    volumes:
      - ./src/AuthService:/app/AuthService
      - ./src/Micro.Shared:/app/Micro.Shared
    working_dir: /app/AuthService/AuthService.API
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80"]
    restart: always

  product-service:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: product-service
    ports:
      - "5002:80"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${PRODUCTDB_CONNECTION}
      - Jwt__Key=${Key}
      - Jwt__Issuer=${Issuer}
      - Jwt__Audience=${Audience}
    volumes:
      - ./src/ProductService:/app/ProductService
      - ./src/Micro.Shared:/app/Micro.Shared
    working_dir: /app/ProductService/ProductService.API
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80"]
    restart: always

  gateway:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: gateway
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    volumes:
      - ./src/ApiGateway:/app/ApiGateway
    working_dir: /app/ApiGateway
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80"]
    restart: always
volumes:
  db_data:
  rd_data:

  # dotnet ef database update --project src/AuthService/AuthService.Infrastructure --startup-project src/AuthService/AuthService.API
  # dotnet ef database update --project src/ProductService/ProductService.Infrastructure --startup-project src/ProductService/ProductService.API
