# yaml refs
# x-refs:
#   common_config: &common_config
#     logging:
#       driver: gelf
#       options:
#         gelf-address: "udp://localhost:12201"

services:
  # nginx-api:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./logs:/var/log/nginx
  #   depends_on:
  #     - gateway
  #     - gateway-2

  auth:
    # <<: *common_config
    image: auth
    volumes:
      - ./logs:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/AuthService/Dockerfile
  ecommerce:
    # <<: *common_config
    image: ecommerce
    volumes:
      - ./logs:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/EcommeceService/Dockerfile
  project:
    # <<: *common_config
    image: project
    volumes:
      - ./logs:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/ProjectService/Dockerfile

  gateway:
    # <<: *common_config
    image: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/ApiGateway/Dockerfile
  gateway-2:
    # <<: *common_config
    image: gateway-2
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/ApiGateway/Dockerfile

  finance:
    # <<: *common_config
    image: finance
    volumes:
      - ./logs:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/FinanceService/Dockerfile
  notification:
    # <<: *common_config
    image: notification
    volumes:
      - ./logs:/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    build:
      context: .
      dockerfile: ./src/NotificationService/Dockerfile
