services:
  auth:
    image: auth
    expose:
      - "8080"
    restart: always
  ecommerce:
    image: ecommerce
    expose:
      - "8080"
    restart: always
  project:
    image: project
    expose:
      - "8080"
    restart: always

  gateway:
    image: gateway
    expose:
      - "8080"
    restart: always
  gateway-2:
    image: gateway-2
    expose:
      - "8080"
    restart: always

  finance:
    image: finance
    expose:
      - "8080"
    restart: always
  notification:
    image: notification
    expose:
      - "8080"
    restart: always
