services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: aspire-dashboard
    ports:
      - "18888:18888" # Cổng web UI
      - "18889:18889" # OTLP/gRPC
      - "18890:18890" # OTLP/HTTP
    environment:
      ASPNETCORE_URLS: "http://+:18888"
      DASHBOARD__OTLP__AUTHMODE: 'ApiKey'
      DASHBOARD__OTLP__PRIMARYAPIKEY: ${ASPIRE_API_KEY}
      DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: "http://+:18889"
      DOTNET_DASHBOARD_OTLP_HTTP_ENDPOINT_URL: "http://+:18890"
    restart: always

  authen:
    container_name: authen
    image: authen
    ports:
      - "8080"
    restart: always
  ecommerce:
    container_name: ecommerce
    image: ecommerce
    ports:
      - "8080"
    restart: always
  project:
    container_name: project
    image: project
    ports:
      - "8080"
    restart: always

  gateway:
    container_name: gateway
    image: gateway
    ports:
      - "8080"
    restart: always

  finance:
    container_name: finance
    image: finance
    ports:
      - "8080"
    restart: always

