<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<PackageReference Include="BCrypt.Net-Next" />
		<PackageReference Include="CliWrap" />
		<PackageReference Include="Mediator.Abstractions" />
		<PackageReference Include="Mediator.SourceGenerator">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="JWT" />
		<PackageReference Include="Wangkanai.Detection" />
		<PackageReference Include="OpenTelemetry" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<Using Include="BCrypt.Net.BCrypt" Static="True" />

	</ItemGroup>
</Project>