// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TheDbContext))]
    [Migration("20250515093254_20250515163241_Project_Migration")]
    partial class _20250515163241_Project_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BehaviorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("behavior_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_fund");

                    b.HasIndex("BehaviorId")
                        .HasDatabaseName("ix_fund_behavior_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_fund_type_id");

                    b.ToTable("fund", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundBehavior", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fund_behavior");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_behavior_id1");

                    b.ToTable("fund_behavior", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fund_type");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_type_id1");

                    b.ToTable("fund_type", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("FromWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_warehouse_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("paid_amount");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("ToWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_warehouse_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("TransactionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_document");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_document_id");

                    b.ToTable("inventory_document", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_invoice");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_invoice_id");

                    b.ToTable("inventory_invoice", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("InventoryDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_document_id");

                    b.Property<long?>("InventoryInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_invoice_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_relation");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_relation_id");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_inventory_relation_inventory_document_id");

                    b.HasIndex("InventoryInvoiceId")
                        .HasDatabaseName("ix_inventory_relation_inventory_invoice_id");

                    b.ToTable("inventory_relation", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("FromWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_warehouse_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("RequestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long?>("ToWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_warehouse_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_request");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_request_id");

                    b.ToTable("inventory_request", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("DiscountType")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("ReceivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_time");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_item_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_order_item_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_order_item_unit_relation_id");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_order_payment");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_payment_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_payment_order_id");

                    b.ToTable("order_payment", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<decimal>("RecommendedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("recommended_price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_product_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_category_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_group_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_group_service");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_service_group_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_group_service_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_group_service_unit_relation_id");

                    b.ToTable("group_service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_category_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_service_id");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_id");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("base_unit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_relation");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_relation_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_unit_relation_service_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_relation_unit_id");

                    b.ToTable("unit_relation", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long?>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<long?>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_service_tariff");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_tariff_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_service_tariff_unit_relation_id");

                    b.HasIndex("TariffId", "ServiceId", "UnitRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_tariff_tariff_id_service_id_unit_relation_id");

                    b.ToTable("service_tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tariff");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_tariff_id");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte?>("CustomerType")
                        .HasColumnType("smallint")
                        .HasColumnName("customer_type");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("day_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("role_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.HasOne("Domain.Aggregates.Funds.FundBehavior", "FundBehavior")
                        .WithMany("Funds")
                        .HasForeignKey("BehaviorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_fund_behavior_behavior_id");

                    b.HasOne("Domain.Aggregates.Funds.FundType", "FundType")
                        .WithMany("Funds")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_fund_type_type_id");

                    b.Navigation("FundBehavior");

                    b.Navigation("FundType");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRelation", b =>
                {
                    b.HasOne("Domain.Aggregates.Inventories.InventoryDocument", "InventoryDocument")
                        .WithMany("InventoryRelationships")
                        .HasForeignKey("InventoryDocumentId")
                        .HasConstraintName("fk_inventory_relation_inventory_document_inventory_document_id");

                    b.HasOne("Domain.Aggregates.Inventories.InventoryInvoice", "InventoryInvoice")
                        .WithMany("InventoryRelationships")
                        .HasForeignKey("InventoryInvoiceId")
                        .HasConstraintName("fk_inventory_relation_inventory_invoice_inventory_invoice_id");

                    b.Navigation("InventoryDocument");

                    b.Navigation("InventoryInvoice");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_order_user_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order_order_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("OrderItems")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_unit_relation_unit_relation_id");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_payment_order_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Group", "Group")
                        .WithMany("GroupServices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_group_group_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("GroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("GroupServices")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_unit_relation_unit_relation_id");

                    b.Navigation("Group");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_service_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("UnitRelations")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_relation_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.Unit", "Unit")
                        .WithMany("UnitRelations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_relation_unit_unit_id");

                    b.Navigation("Service");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_service_tariff_service_service_id");

                    b.HasOne("Domain.Aggregates.Tariffs.Tariff", "Tariff")
                        .WithMany("ServiceTariffs")
                        .HasForeignKey("TariffId")
                        .HasConstraintName("fk_service_tariff_tariff_tariff_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany()
                        .HasForeignKey("UnitRelationId")
                        .HasConstraintName("fk_service_tariff_unit_relation_unit_relation_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundBehavior", b =>
                {
                    b.Navigation("Funds");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundType", b =>
                {
                    b.Navigation("Funds");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryDocument", b =>
                {
                    b.Navigation("InventoryRelationships");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryInvoice", b =>
                {
                    b.Navigation("InventoryRelationships");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Navigation("GroupServices");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Navigation("GroupServices");

                    b.Navigation("OrderItems");

                    b.Navigation("UnitRelations");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Unit", b =>
                {
                    b.Navigation("UnitRelations");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Navigation("GroupServices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Navigation("ServiceTariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
