// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TheDbContext))]
    [Migration("20250715014046_20250715084003_Ecommerce_Migration")]
    partial class _20250715084003_Ecommerce_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Equipments.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_maintenance_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_maintenance_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.EquipmentActivity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("EquipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_id");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("numeric")
                        .HasColumnName("labor_cost");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("text")
                        .HasColumnName("received_by");

                    b.Property<DateTimeOffset?>("ReportedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_date");

                    b.Property<DateTimeOffset?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SupervisorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supervisor_code");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_cost");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_equipment_activity");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_equipment_activity_equipment_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_equipment_activity_staff_id");

                    b.ToTable("equipment_activity", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.EquipmentActivityDetail", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EquipmentActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_activity_id");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_equipment_activity_detail");

                    b.HasIndex("EquipmentActivityId")
                        .HasDatabaseName("ix_equipment_activity_detail_equipment_activity_id");

                    b.ToTable("equipment_activity_detail", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.EquipmentSupplying", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("InventoryDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_document_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_supplying");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_equipment_supplying_inventory_document_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_equipment_supplying_supplier_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_equipment_supplying_unit_relation_id");

                    b.ToTable("equipment_supplying", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryDocument", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("FromWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_warehouse_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("paid_amount");

                    b.Property<byte?>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long?>("ToWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_warehouse_id");

                    b.Property<DateTimeOffset?>("TransactionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_document");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_document_id");

                    b.ToTable("inventory_document", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryInvoice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset>("TransactionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_invoice");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_invoice_id");

                    b.ToTable("inventory_invoice", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRelation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("InventoryDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_document_id");

                    b.Property<long?>("InventoryInvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_relation");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_relation_id");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_inventory_relation_inventory_document_id");

                    b.HasIndex("InventoryInvoiceId")
                        .HasDatabaseName("ix_inventory_relation_inventory_invoice_id");

                    b.ToTable("inventory_relation", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRequest", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("FromWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_warehouse_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("RequestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long?>("ToWarehouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_warehouse_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_request");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_inventory_request_id");

                    b.ToTable("inventory_request", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.ProductSupplying", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<long>("InventoryDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_document_id");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_product_supplying");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_product_supplying_id");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_product_supplying_inventory_document_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_supplying_product_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_product_supplying_supplier_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_product_supplying_unit_relation_id");

                    b.ToTable("product_supplying", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("DeliveryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_time");

                    b.Property<bool>("DiscountFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_fixed");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("Receipt")
                        .HasColumnType("text")
                        .HasColumnName("receipt");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_order_staff_id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("ProcessingTime")
                        .HasColumnType("numeric")
                        .HasColumnName("processing_time");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.Property<string>("UnitRelationName")
                        .HasColumnType("text")
                        .HasColumnName("unit_relation_name");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_item_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_order_item_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_order_item_unit_relation_id");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.HasKey("Id")
                        .HasName("pk_order_payment");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_payment_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_payment_order_id");

                    b.ToTable("order_payment", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Prints.PrintTemplate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("HtmlTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_print_template");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_print_template_id");

                    b.ToTable("print_template", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Products.BranchProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<decimal>("CapitalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("capital_price");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_branch_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_branch_product_category_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_branch_product_id");

                    b.ToTable("branch_product", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_category_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_group_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_group_service");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_service_group_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_group_service_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_group_service_unit_relation_id");

                    b.ToTable("group_service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_category_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_service_id");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_id");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("BaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("base_unit");

                    b.Property<long?>("BranchProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_product_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Multiple")
                        .HasColumnType("integer")
                        .HasColumnName("multiple");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("ProcessingTime")
                        .HasColumnType("numeric")
                        .HasColumnName("processing_time");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_unit_relation");

                    b.HasIndex("BranchProductId")
                        .HasDatabaseName("ix_unit_relation_branch_product_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_relation_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_unit_relation_service_id");

                    b.ToTable("unit_relation", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_supplier_id");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServicePriceTariffHistory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_service_price_tariff_history");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_price_tariff_history_service_id");

                    b.HasIndex("TariffId", "ServiceId", "UnitRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_price_tariff_history_tariff_id_service_id_unit_rela");

                    b.ToTable("service_price_tariff_history", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_service_tariff");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_tariff_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_service_tariff_unit_relation_id");

                    b.HasIndex("TariffId", "ServiceId", "UnitRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_tariff_tariff_id_service_id_unit_relation_id");

                    b.ToTable("service_tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tariff");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_tariff_id");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.BranchUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("BranchName")
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_branch_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_branch_user_user_id");

                    b.ToTable("branch_user", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AvtUrl")
                        .HasColumnType("text")
                        .HasColumnName("avt_url");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birth_day");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<short?>("CustomerGroup")
                        .HasColumnType("smallint")
                        .HasColumnName("customer_group");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_user_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Vouchers.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("DiscountFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_fixed");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_url");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_voucher");

                    b.ToTable("voucher", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Vouchers.VoucherCustomer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<long>("VoucherId")
                        .HasColumnType("bigint")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("pk_voucher_customer");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_voucher_customer_customer_id");

                    b.HasIndex("VoucherId")
                        .HasDatabaseName("ix_voucher_customer_voucher_id");

                    b.ToTable("voucher_customer", (string)null);
                });

            modelBuilder.Entity("Domain.Functions.CustomerRevenueResult", b =>
                {
                    b.Property<string>("AvtUrl")
                        .HasColumnType("text")
                        .HasColumnName("avt_url");

                    b.Property<decimal>("CancelValue")
                        .HasColumnType("numeric")
                        .HasColumnName("cancel_value");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("text")
                        .HasColumnName("customer_code");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<decimal>("NetRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("net_revenue");

                    b.Property<int>("OrderCancelQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("order_cancel_quantity");

                    b.Property<int>("OrderSaleQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("order_sale_quantity");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.ToTable("customer_revenue_result", (string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Domain.Functions.GetRevenueStatistic", b =>
                {
                    b.Property<DateOnly>("RevenueDate")
                        .HasColumnType("date")
                        .HasColumnName("revenue_date");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_revenue");

                    b.ToTable("get_revenue_statistic", (string)null);
                });

            modelBuilder.Entity("Domain.Functions.OrderSummaryResult", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("order_item_count");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.ToTable("order_summary_result", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.EquipmentActivity", b =>
                {
                    b.HasOne("Domain.Aggregates.Equipments.Equipment", "Equipment")
                        .WithMany("EquipmentActivities")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_activity_equipment_equipment_id");

                    b.HasOne("Domain.Aggregates.Users.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_activity_user_staff_id");

                    b.Navigation("Equipment");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.EquipmentActivityDetail", b =>
                {
                    b.HasOne("Domain.Aggregates.Equipments.EquipmentActivity", "EquipmentActivity")
                        .WithMany("ActivityDetails")
                        .HasForeignKey("EquipmentActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_activity_detail_equipment_activity_equipment_acti");

                    b.Navigation("EquipmentActivity");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.EquipmentSupplying", b =>
                {
                    b.HasOne("Domain.Aggregates.Inventories.InventoryDocument", "InventoryDocument")
                        .WithMany("EquipmentSupplyings")
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_supplying_inventory_document_inventory_document_id");

                    b.HasOne("Domain.Aggregates.Suppliers.Supplier", "Supplier")
                        .WithMany("EquipmentSupplyings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_supplying_supplier_supplier_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("EquipmentSupplyings")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_supplying_unit_relation_unit_relation_id");

                    b.Navigation("InventoryDocument");

                    b.Navigation("Supplier");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryRelation", b =>
                {
                    b.HasOne("Domain.Aggregates.Inventories.InventoryDocument", "InventoryDocument")
                        .WithMany("InventoryRelationships")
                        .HasForeignKey("InventoryDocumentId")
                        .HasConstraintName("fk_inventory_relation_inventory_document_inventory_document_id");

                    b.HasOne("Domain.Aggregates.Inventories.InventoryInvoice", "InventoryInvoice")
                        .WithMany("InventoryRelationships")
                        .HasForeignKey("InventoryInvoiceId")
                        .HasConstraintName("fk_inventory_relation_inventory_invoice_inventory_invoice_id");

                    b.Navigation("InventoryDocument");

                    b.Navigation("InventoryInvoice");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.ProductSupplying", b =>
                {
                    b.HasOne("Domain.Aggregates.Inventories.InventoryDocument", "InventoryDocument")
                        .WithMany("ProductSupplyings")
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_inventory_document_inventory_document_id");

                    b.HasOne("Domain.Aggregates.Products.BranchProduct", null)
                        .WithMany("ProductSupplyings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_branch_product_product_id");

                    b.HasOne("Domain.Aggregates.Suppliers.Supplier", "Supplier")
                        .WithMany("ProductSupplyings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_supplier_supplier_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("ProductSupplyings")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_unit_relation_unit_relation_id");

                    b.Navigation("InventoryDocument");

                    b.Navigation("Supplier");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_order_user_customer_id");

                    b.HasOne("Domain.Aggregates.Users.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_user_staff_id");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order_order_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("OrderItems")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_unit_relation_unit_relation_id");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_payment_order_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Aggregates.Products.BranchProduct", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_product_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Group", "Group")
                        .WithMany("GroupServices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_group_group_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("GroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany()
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_unit_relation_unit_relation_id");

                    b.Navigation("Group");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.HasOne("Domain.Aggregates.Products.BranchProduct", "BranchProduct")
                        .WithMany("UnitRelations")
                        .HasForeignKey("BranchProductId")
                        .HasConstraintName("fk_unit_relation_branch_product_branch_product_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("UnitRelations")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_unit_relation_service_service_id");

                    b.Navigation("BranchProduct");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServicePriceTariffHistory", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("ServicePriceTariffHistories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_price_tariff_history_service_service_id");

                    b.HasOne("Domain.Aggregates.Tariffs.Tariff", "Tariff")
                        .WithMany("ServicePriceTariffHistories")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_price_tariff_history_tariff_tariff_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_service_service_id");

                    b.HasOne("Domain.Aggregates.Tariffs.Tariff", "Tariff")
                        .WithMany("ServiceTariffs")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_tariff_tariff_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany()
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_unit_relation_unit_relation_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.BranchUser", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", null)
                        .WithMany("BranchUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_user_user_user_id");
                });

            modelBuilder.Entity("Domain.Aggregates.Vouchers.VoucherCustomer", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_customer_user_customer_id");

                    b.HasOne("Domain.Aggregates.Vouchers.Voucher", "Voucher")
                        .WithMany("VoucherCustomers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_customer_voucher_voucher_id");

                    b.Navigation("Customer");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.Equipment", b =>
                {
                    b.Navigation("EquipmentActivities");
                });

            modelBuilder.Entity("Domain.Aggregates.Equipments.EquipmentActivity", b =>
                {
                    b.Navigation("ActivityDetails");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryDocument", b =>
                {
                    b.Navigation("EquipmentSupplyings");

                    b.Navigation("InventoryRelationships");

                    b.Navigation("ProductSupplyings");
                });

            modelBuilder.Entity("Domain.Aggregates.Inventories.InventoryInvoice", b =>
                {
                    b.Navigation("InventoryRelationships");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("Domain.Aggregates.Products.BranchProduct", b =>
                {
                    b.Navigation("ProductSupplyings");

                    b.Navigation("UnitRelations");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Navigation("GroupServices");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Navigation("GroupServices");

                    b.Navigation("OrderItems");

                    b.Navigation("ServicePriceTariffHistories");

                    b.Navigation("UnitRelations");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Navigation("EquipmentSupplyings");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductSupplyings");
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.Supplier", b =>
                {
                    b.Navigation("EquipmentSupplyings");

                    b.Navigation("ProductSupplyings");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Navigation("ServicePriceTariffHistories");

                    b.Navigation("ServiceTariffs");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("BranchUsers");
                });

            modelBuilder.Entity("Domain.Aggregates.Vouchers.Voucher", b =>
                {
                    b.Navigation("VoucherCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
