// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TheDbContext))]
    partial class TheDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BehaviorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("behavior_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_fund");

                    b.HasIndex("BehaviorId")
                        .HasDatabaseName("ix_fund_behavior_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_fund_order_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_fund_type_id");

                    b.ToTable("fund", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundBehavior", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fund_behavior");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_behavior_id1");

                    b.ToTable("fund_behavior", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fund_type");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_fund_type_id1");

                    b.ToTable("fund_type", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("DeliveryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_time");

                    b.Property<bool>("DiscountFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("discount_fixed");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_item_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_order_item_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_order_item_unit_relation_id");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("smallint")
                        .HasColumnName("payment_method");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_order_payment");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_order_payment_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_payment_order_id");

                    b.ToTable("order_payment", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Prints.PrintTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("HtmlTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_print_template");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_print_template_id");

                    b.ToTable("print_template", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<short>("status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_category_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("citext")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_group_id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.HasKey("Id")
                        .HasName("pk_group_service");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_service_group_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_group_service_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_group_service_unit_relation_id");

                    b.ToTable("group_service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_category_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_service_id");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_id");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("base_unit");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Multiple")
                        .HasColumnType("integer")
                        .HasColumnName("multiple");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("ProcessingTime")
                        .HasColumnType("numeric")
                        .HasColumnName("processing_time");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_relation");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_unit_relation_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_unit_relation_reference_id");

                    b.ToTable("unit_relation", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.ProductSupplying", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ArriveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrive_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExperyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expery_date");

                    b.Property<long>("InvetoryDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("invetory_document_id");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lot_number");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long?>("SupplierId1")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id1");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_product_supplying");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_product_supplying_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_product_supplying_supplier_id");

                    b.HasIndex("SupplierId1")
                        .HasDatabaseName("ix_product_supplying_supplier_id1");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_product_supplying_unit_id");

                    b.ToTable("product_supplying", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_supplier_id");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServicePriceTariffHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_service_price_tariff_history");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_price_tariff_history_service_id");

                    b.HasIndex("TariffId", "ServiceId", "UnitRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_price_tariff_history_tariff_id_service_id_unit_rela");

                    b.ToTable("service_price_tariff_history", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<long>("UnitRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_relation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_service_tariff");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_tariff_service_id");

                    b.HasIndex("UnitRelationId")
                        .HasDatabaseName("ix_service_tariff_unit_relation_id");

                    b.HasIndex("TariffId", "ServiceId", "UnitRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_tariff_tariff_id_service_id_unit_relation_id");

                    b.ToTable("service_tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Disable")
                        .HasColumnType("boolean")
                        .HasColumnName("disable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tariff");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_tariff_id");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<byte?>("CustomerType")
                        .HasColumnType("smallint")
                        .HasColumnName("customer_type");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("day_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("role_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_user_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint")
                        .HasColumnName("branch_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("public_id");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_level");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_warehouse");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_warehouse_id");

                    b.ToTable("warehouse", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.Fund", b =>
                {
                    b.HasOne("Domain.Aggregates.Funds.FundBehavior", "FundBehavior")
                        .WithMany("Funds")
                        .HasForeignKey("BehaviorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_fund_behavior_behavior_id");

                    b.HasOne("Domain.Aggregates.Orders.Order", null)
                        .WithMany("Funds")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_fund_order_order_id");

                    b.HasOne("Domain.Aggregates.Funds.FundType", "FundType")
                        .WithMany("Funds")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fund_fund_type_type_id");

                    b.Navigation("FundBehavior");

                    b.Navigation("FundType");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.HasOne("Domain.Aggregates.Users.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_user_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderItem", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order_order_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("OrderItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany("OrderItems")
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_unit_relation_unit_relation_id");

                    b.Navigation("Order");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.OrderPayment", b =>
                {
                    b.HasOne("Domain.Aggregates.Orders.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_payment_order_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.GroupService", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Group", "Group")
                        .WithMany("GroupServices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_group_group_id");

                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("GroupServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_service_service_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany()
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_service_unit_relation_unit_relation_id");

                    b.Navigation("Group");

                    b.Navigation("Service");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("UnitRelations")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_relation_service_reference_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.ProductSupplying", b =>
                {
                    b.HasOne("Domain.Aggregates.Suppliers.Supplier", "Suppliers")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_supplier_supplier_id");

                    b.HasOne("Domain.Aggregates.Suppliers.Supplier", null)
                        .WithMany("ProductSupplyings")
                        .HasForeignKey("SupplierId1")
                        .HasConstraintName("fk_product_supplying_supplier_supplier_id1");

                    b.HasOne("Domain.Aggregates.Services.Unit", "Units")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_supplying_unit_unit_id");

                    b.Navigation("Suppliers");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServicePriceTariffHistory", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany("ServicePriceTariffHistories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_price_tariff_history_service_service_id");

                    b.HasOne("Domain.Aggregates.Tariffs.Tariff", "Tariff")
                        .WithMany("ServicePriceTariffHistories")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_price_tariff_history_tariff_tariff_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.ServiceTariff", b =>
                {
                    b.HasOne("Domain.Aggregates.Services.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_service_service_id");

                    b.HasOne("Domain.Aggregates.Tariffs.Tariff", "Tariff")
                        .WithMany("ServiceTariffs")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_tariff_tariff_id");

                    b.HasOne("Domain.Aggregates.Services.UnitRelation", "UnitRelation")
                        .WithMany()
                        .HasForeignKey("UnitRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_tariff_unit_relation_unit_relation_id");

                    b.Navigation("Service");

                    b.Navigation("Tariff");

                    b.Navigation("UnitRelation");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundBehavior", b =>
                {
                    b.Navigation("Funds");
                });

            modelBuilder.Entity("Domain.Aggregates.Funds.FundType", b =>
                {
                    b.Navigation("Funds");
                });

            modelBuilder.Entity("Domain.Aggregates.Orders.Order", b =>
                {
                    b.Navigation("Funds");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Group", b =>
                {
                    b.Navigation("GroupServices");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.Service", b =>
                {
                    b.Navigation("GroupServices");

                    b.Navigation("OrderItems");

                    b.Navigation("ServicePriceTariffHistories");

                    b.Navigation("UnitRelations");
                });

            modelBuilder.Entity("Domain.Aggregates.Services.UnitRelation", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Aggregates.Suppliers.Supplier", b =>
                {
                    b.Navigation("ProductSupplyings");
                });

            modelBuilder.Entity("Domain.Aggregates.Tariffs.Tariff", b =>
                {
                    b.Navigation("ServicePriceTariffHistories");

                    b.Navigation("ServiceTariffs");
                });
#pragma warning restore 612, 618
        }
    }
}
