<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="moq" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <None Include="..\..\..\src\AuthService\Presentation\Resources\Translations\Message.en.resx">
      <Link>Resources\Translations\Message.en.resx</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\src\AuthService\Presentation\Resources\Translations\Message.vi.resx">
      <Link>Resources\Translations\Message.vi.resx</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\AuthService\Application\Application.csproj" />
    <ProjectReference Include="..\..\..\src\Contracts\Contracts.csproj" />
  </ItemGroup>
</Project>